### ISSUE TITLE
Alpha Docker Image Service

### ISSUE THREAD

**Issue by DevArKaDiA** [DevArKaDiA/whatsapp-web.js-service#5]
## Notes:

- PuppeterJS need some requirementes for work console only linux system take a look in

![Image](https://github.com/DevArKaDiA/whatsapp-web.js-service/assets/15362561/65818cfc-1d5e-4e18-a6b3-127a00ba9615)

`$ sudo apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
`

[`Installation Whatsappweb js`](https://wwebjs.dev/guide/#installation)
- Expose the 3000 Port for give access to the Api Rest to users. WARNING (NO AUTH IMPLEMENTED)
- Also the service need internet access for make the WebHook calls

**Comment by DevArKaDiA** [comment]
## Notes:

- PuppeterJS need some requirementes for work console only linux system take a look in


![Image](https://github.com/DevArKaDiA/whatsapp-web.js-service/assets/15362561/65818cfc-1d5e-4e18-a6b3-127a00ba9615)

`$ sudo apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
`

[`Installation Whatsappweb js`](https://wwebjs.dev/guide/#installation)
- Expose the 3000 Port for give access to the Api Rest to users. WARNING (NO AUTH IMPLEMENTED)
- Also the service need internet access for make the WebHook calls

**Comment by DevArKaDiA** [comment]
## Api Rest - WebHook Whatsappweb.js  ![image](https://github.com/DevArKaDiA/whatsapp-web.js-service/assets/15362561/6cf25cc7-6d9a-472e-b840-b064fbc3f135) - Service Image 

Credits: @pedroslopez - Creator of whatsapp-web.js
Official Repo [https://github.com/pedroslopez/whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js)

-----

Docker Hub: [arkadia0315/whatsappweb-js-service](https://hub.docker.com/r/arkadia0315/whatsappweb-js-service)

The aim of this Image is make a lenguaje agnostic interface for whatsappwebjs library using a webhook event system and a rest Api to interact with the library using any programing lenguaje.

### RoadMap:

- [x]  (NO AUTH) Hook System
- [x]  SUB - UNSUB - Hook peer events System
- [x]  Hook Endpoint calling per Event subcribed
- [x]  Docker Support
- [x]  Send Msg Endpoints (Raw String MSG)
- [ ]  Add Multimedia support for Msg endpoint
- [ ]  List Chats Endpoints
- [ ]   Get Chat Msgs Endpoints

**Comment by DevArKaDiA** [comment]
Merged
